const propertyDataSeed = [
    {
      userEmail: "seller1@example.com",
      userLikes: 5,
      address: "123 Main St, Cityville",
      listingPrice: "$300,000",
      yearBuilt: "2001",
      totalSquareFootage: "1500 sqft",
      bedrooms: "3",
      bathrooms: "2",
      floors: "2",
      localAmenities: "Park, School, Shopping Mall",
      sellerMobile: "123-456-7890",
      openTime: "10:00 AM - 2:00 PM"
    },
    {
      userEmail: "seller2@example.com",
      userLikes: 10,
      address: "456 Elm St, Townsville",
      listingPrice: "$400,000",
      yearBuilt: "1995",
      totalSquareFootage: "2000 sqft",
      bedrooms: "4",
      bathrooms: "3",
      floors: "2",
      localAmenities: "Hospital, Grocery Store, Library",
      sellerMobile: "234-567-8901",
      openTime: "11:00 AM - 3:00 PM"
    },
    {
      userEmail: "seller1@example.com",
      userLikes: 3,
      address: "789 Oak St, Villagetown",
      listingPrice: "$250,000",
      yearBuilt: "2010",
      totalSquareFootage: "1200 sqft",
      bedrooms: "2",
      bathrooms: "2",
      floors: "1",
      localAmenities: "Park, Restaurant, Gym",
      sellerMobile: "345-678-9012",
      openTime: "9:00 AM - 12:00 PM"
    },
    {
      userEmail: "seller1@example.com",
      userLikes: 7,
      address: "101 Pine St, Hamletville",
      listingPrice: "$500,000",
      yearBuilt: "2005",
      totalSquareFootage: "2200 sqft",
      bedrooms: "5",
      bathrooms: "4",
      floors: "3",
      localAmenities: "School, Shopping Mall, Library",
      sellerMobile: "456-789-0123",
      openTime: "1:00 PM - 4:00 PM"
    },
    {
      userEmail: "seller2@example.com",
      userLikes: 12,
      address: "202 Birch St, Citytown",
      listingPrice: "$350,000",
      yearBuilt: "1990",
      totalSquareFootage: "1800 sqft",
      bedrooms: "3",
      bathrooms: "2",
      floors: "2",
      localAmenities: "Grocery Store, Gym, Restaurant",
      sellerMobile: "567-890-1234",
      openTime: "2:00 PM - 5:00 PM"
    },
    {
      userEmail: "seller3@example.com",
      userLikes: 4,
      address: "303 Cedar St, Suburbia",
      listingPrice: "$450,000",
      yearBuilt: "2008",
      totalSquareFootage: "2100 sqft",
      bedrooms: "4",
      bathrooms: "3",
      floors: "2",
      localAmenities: "Park, School, Hospital",
      sellerMobile: "678-901-2345",
      openTime: "10:00 AM - 1:00 PM"
    },
    {
      userEmail: "seller3@example.com",
      userLikes: 8,
      address: "404 Walnut St, Countryside",
      listingPrice: "$600,000",
      yearBuilt: "2015",
      totalSquareFootage: "2500 sqft",
      bedrooms: "5",
      bathrooms: "4",
      floors: "3",
      localAmenities: "Restaurant, Gym, Library",
      sellerMobile: "789-012-3456",
      openTime: "11:00 AM - 2:00 PM"
    },
    {
      userEmail: "seller4@example.com",
      userLikes: 6,
      address: "505 Maple St, Metropolis",
      listingPrice: "$700,000",
      yearBuilt: "2012",
      totalSquareFootage: "3000 sqft",
      bedrooms: "6",
      bathrooms: "5",
      floors: "3",
      localAmenities: "Shopping Mall, Gym, Hospital",
      sellerMobile: "890-123-4567",
      openTime: "12:00 PM - 3:00 PM"
    },
    {
      userEmail: "seller1@example.com",
      userLikes: 9,
      address: "606 Ash St, Downtown",
      listingPrice: "$550,000",
      yearBuilt: "2000",
      totalSquareFootage: "2400 sqft",
      bedrooms: "4",
      bathrooms: "3",
      floors: "2",
      localAmenities: "School, Grocery Store, Park",
      sellerMobile: "901-234-5678",
      openTime: "9:00 AM - 12:00 PM"
    },
    {
      userEmail: "seller1@example.com",
      userLikes: 2,
      address: "707 Cherry St, Uptown",
      listingPrice: "$320,000",
      yearBuilt: "1998",
      totalSquareFootage: "1600 sqft",
      bedrooms: "3",
      bathrooms: "2",
      floors: "1",
      localAmenities: "Hospital, Restaurant, Gym",
      sellerMobile: "012-345-6789",
      openTime: "8:00 AM - 11:00 AM"
    }
  ];

export default propertyDataSeed;
  