const propertyDataSeed = [
  {
    userEmail: "seller4@example.com",
    likes: 10,
    address: "15 MG Road, Bengaluru",
    cost: 25000,
    city: "Bengaluru",
    yearBuilt: 2010,
    area: 1500,
    bedrooms: 3,
    bathrooms: 2,
    floors: 1,
    amenities: ["Park", "Gym", "Swimming Pool"],
    visitTimings: "9 AM - 5 PM",
    type: "Apartment"
  },
  {
    userEmail: "seller1@example.com",
    likes: 20,
    address: "220 Lodhi Road, New Delhi",
    cost: 50000,
    city: "Delhi",
    yearBuilt: 2005,
    area: 2500,
    bedrooms: 4,
    bathrooms: 3,
    floors: 2,
    amenities: ["Metro", "Mall", "School"],
    visitTimings: "10 AM - 6 PM",
    type: "Villa"
  },
  {
    userEmail: "seller2@example.com",
    likes: 15,
    address: "89 Juhu Beach, Mumbai",
    cost: 75000,
    city: "Mumbai",
    yearBuilt: 2012,
    area: 3000,
    bedrooms: 5,
    bathrooms: 3,
    floors: 3,
    amenities: ["Beach", "Restaurant", "Hospital"],
    visitTimings: "8 AM - 4 PM",
    type: "Bungalow"
  },
  {
    userEmail: "seller3@example.com",
    likes: 5,
    address: "45 Nehru Place, Chennai",
    cost: 20000,
    city: "Chennai",
    yearBuilt: 2018,
    area: 1400,
    bedrooms: 2,
    bathrooms: 2,
    floors: 1,
    amenities: ["Park", "Supermarket", "Gym"],
    visitTimings: "9 AM - 5 PM",
    type: "Apartment"
  },
  {
    userEmail: "seller2@example.com",
    likes: 30,
    address: "77 Golf Course Road, Kolkata",
    cost: 60000,
    city: "Kolkata",
    yearBuilt: 2007,
    area: 2000,
    bedrooms: 4,
    bathrooms: 3,
    floors: 2,
    amenities: ["Golf Club", "Restaurant", "Gym"],
    visitTimings: "10 AM - 6 PM",
    type: "Villa"
  },
  {
    userEmail: "seller1@example.com",
    likes: 8,
    address: "88 M G Road, Pune",
    cost: 35000,
    city: "Pune",
    yearBuilt: 2015,
    area: 1800,
    bedrooms: 3,
    bathrooms: 2,
    floors: 2,
    amenities: ["Mall", "School", "Hospital"],
    visitTimings: "9 AM - 5 PM",
    type: "Apartment"
  },
  {
    userEmail: "seller2@example.com",
    likes: 12,
    address: "101 Main Road, Hyderabad",
    cost: 40000,
    city: "Hyderabad",
    yearBuilt: 2010,
    area: 2200,
    bedrooms: 4,
    bathrooms: 3,
    floors: 1,
    amenities: ["School", "Supermarket", "Park"],
    visitTimings: "8 AM - 4 PM",
    type: "House"
  },
  {
    userEmail: "seller3@example.com",
    likes: 18,
    address: "75 R A Puram, Chennai",
    cost: 45000,
    city: "Chennai",
    yearBuilt: 2008,
    area: 2000,
    bedrooms: 3,
    bathrooms: 2,
    floors: 2,
    amenities: ["Hospital", "Mall", "Gym"],
    visitTimings: "10 AM - 6 PM",
    type: "Apartment"
  },
  {
    userEmail: "seller2@example.com",
    likes: 22,
    address: "35 Park Street, Kolkata",
    cost: 55000,
    city: "Kolkata",
    yearBuilt: 2013,
    area: 2400,
    bedrooms: 4,
    bathrooms: 3,
    floors: 3,
    amenities: ["Park", "Restaurant", "Supermarket"],
    visitTimings: "9 AM - 5 PM",
    type: "Bungalow"
  },
  {
    userEmail: "seller1@example.com",
    likes: 25,
    address: "65 JP Nagar, Bengaluru",
    cost: 30000,
    city: "Bengaluru",
    yearBuilt: 2011,
    area: 1600,
    bedrooms: 3,
    bathrooms: 2,
    floors: 1,
    amenities: ["School", "Hospital", "Gym"],
    visitTimings: "10 AM - 6 PM",
    type: "Apartment"
  }
];

export default propertyDataSeed;